### ISSUE TITLE
Joining ISUmonarch::length

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch_figuresAndTables#1]
In the `nectar_density_table` function, there is code to left join the`ISUmonarch::length` dataset. Do we want to comment this out just to get it running?

@jarad @sethapp

**Comment by jarad** [comment]
Honestly, I don't remember what this function is meant to do. I'm guessing you need the length later. So commenting it out may make the function run (although I doubt it), but I'm guessing it will give you incorrect answers. So probably better to figure out what intended and fix it.

**Comment by nulloa** [comment]
So it looks like the length dataset and script was renamed to survey per jarad/ISUmonarch@18cc5a76b0352181a7f7668d2e169d1c113e79a7 and the original length script: jarad/ISUmonarch@fa686aef23bcc98421e002a4b7c8ccbed1d9fec8

I'm going to look into changing length to survey and see if it produces the correct output.

**Comment by nulloa** [comment]
So this has not been updated in a while, but there is once again a dataset named survey. We link nectar to it by first joining transect then joining survey.

@sethapp I have a question, does it make sense that the same transect for the same year would have different lengths?

```
> subtrans = subset(ISUmonarch::survey, year==2016) %>% select(transectID, length)
> head(subtrans)
  transectID length
1     tbyd1a    100
2     tbyd2a    100
3     tcra1a     70
4     tuth1a    100
5     tuth2a    100
7     tall1a     50
> subtrans %>% group_by(transectID) %>% summarise(num = length(unique(length))) %>% filter(num > 1)
# A tibble: 5 x 2
  transectID   num
  <fct>      <int>
1 tcre1a         2
2 tnkn1a         2
3 tnkn2a         2
4 tpre1a         2
5 tsie1a         2
```

**Comment by sethapp** [comment]
@nulloa It should not have happened but yes it did occur. Sometimes survey crews thought the transect was shorter than it really was and stopped collecting data before the end of the transect. Also, sometimes the transect was permanently shortened because the end of it was destroyed by a farmer.

**Comment by nulloa** [comment]
This has been decided the correct way to deal with this is to create a density measurement per transect per round then avg over round.
