### ISSUE TITLE
Daubenmire Table

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#15]
We can remove the 'mean' row from the bottom of the table.

Obviously, add in 2018 data and all the sites.

litter depth should contain one decimal point (all other data should not).

The 'diff' column is not useful anymore because we have multiple years, with 2019 to be added. It should be removed. Other than the line graphs I have proposed in issue #14 I'm not sure how we could best (or even should) show declines or increases in a table format. Maybe attempting to visually show something would be overwhelming. Maybe we color code each cell. Leave the numbers in the cells (basically filling the cell as you would in excel): red cells indicate declines and green cells indicate increases from the previous year?

Once PCA has been done we could also group sites into clusters to reduce number of rows and be able to say something about clusters of sites instead of single sites.

@jarad your thoughts would be appreciated

**Comment by nulloa** [comment]
Convert `litter depth` to mm from cm

**Comment by nulloa** [comment]
Should there be different tables for `cover` and `litter`? Or do you want it on the same table like last time?

```
> head(cover)
  year month day siteID transectID round section                   observer class percentage
1 2016     6  27   nie1     tnie1a     1      0m JaclynAKelseyFSydneyHCoryH   csg         38
2 2016     6  27   nie1     tnie1a     1     10m JaclynAKelseyFSydneyHCoryH   csg         38
3 2016     6  27   nie1     tnie1a     1     20m JaclynAKelseyFSydneyHCoryH   csg         63
4 2016     6  27   nie1     tnie1a     1     30m JaclynAKelseyFSydneyHCoryH   csg         38
5 2016     6  27   nie1     tnie1a     1     40m JaclynAKelseyFSydneyHCoryH   csg         38
6 2016     6  27   dav1     tdav1a     1      0m             JaclynASydneyH   csg         38
> head(litter)
  year month day siteID transectID round section                   observer depth
1 2016     6  27   nie1     tnie1a     1      0m JaclynAKelseyFSydneyHCoryH     2
2 2016     6  27   nie1     tnie1a     1     10m JaclynAKelseyFSydneyHCoryH     3
3 2016     6  27   nie1     tnie1a     1     20m JaclynAKelseyFSydneyHCoryH     1
4 2016     6  27   nie1     tnie1a     1     30m JaclynAKelseyFSydneyHCoryH     2
5 2016     6  27   nie1     tnie1a     1     40m JaclynAKelseyFSydneyHCoryH     9
6 2016     6  27   dav1     tdav1a     1      0m             JaclynASydneyH     6
```

**Comment by nulloa** [comment]
The first pass at the table is in 5ddb1ae2e1fc6d3d48c292cad42a01d8a9cad11d. As it stands the table fits in one page.

**Comment by sethapp** [comment]
I think same table is good we just need to note in the column header that it's litter depth (mm)

**Comment by nulloa** [comment]
Create same table for
```
> head(milkweed)
  year month day siteID transectID round section           observer milkweed_species ramets
1 2017     6  15   ber1     tber1a     1      0m CoryHSydneyHNancyS     common_ramet      0
2 2017     6  15   ber1     tber1a     1     10m CoryHSydneyHNancyS     common_ramet      0
3 2017     6  15   ber1     tber1a     1     20m CoryHSydneyHNancyS     common_ramet      0
4 2017     6  15   ber1     tber1a     1     30m CoryHSydneyHNancyS     common_ramet      0
5 2017     6  15   ber1     tber1a     1     40m CoryHSydneyHNancyS     common_ramet      0
6 2017     6  15   ber3     tber3a     1      0m CoryHSydneyHNancyS     common_ramet      0
```

**Comment by nulloa** [comment]
This has been done in efb4fb78888b84890e37bbe01f033df969197adf

**Comment by sethapp** [comment]
The Daubemire milkweed table has a vertical border line that is in the wrong column. vertical lines should run between each milkweed species
