### ISSUE TITLE
Robel Table

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#16]
We could make a table similar to what I described in issue #15 Daubenmire Table.

> Maybe we color code each cell. Leave the numbers in the cells (basically filling the cell as you would in excel): red cells indicate declines and green cells indicate increases from the previous year?

> Once PCA has been done we could also group sites into clusters to reduce number of rows and be able to say something about clusters of sites instead of single sites.

Obviously, add in 2018 data and all the sites.

**Comment by nulloa** [comment]
First pass is at bb08a3ea54fcf80117424b0de09f13eec368f843

**Comment by sethapp** [comment]
I would like all values in the table to have one value following the decimal point so that they all line up vertically on the decimal

**Comment by nulloa** [comment]
All done 9110b5cd5c393de04d2fbb14284ff7595350f7fe
