### ISSUE TITLE
Robel Figure

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#17]
To display the robel data visually we could use a line graph.

First statement: The suggestions below allow more than one site/group to be shown on a single graph but would need to limit the number to prevent it from being overwhelming. 

Line graphs:
x axis: year (2016,2017,2018,[2019])
y axis: visual obstruction reading (in cm)
Different line for each site or group
-once sites are grouped with PCA we may be able to show something interesting with multiple groups on same graph

**Comment by nulloa** [comment]
See the first pass here bb08a3ea54fcf80117424b0de09f13eec368f843
