### ISSUE TITLE
Monarch Table

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#18]
We can retain the original setup of the monarch table with the following modifications.

Add in 2018 data. 

'total' and 'survey' do not need to be changed.

**Ramets**

- '2016 ramets' if this could say '2016 milkweed ramets' that would be better but it's fine if it remains '2016 ramets'. In 2016 we did not differentiate between milkweed species.

- 2017 and years following ramets should be broken out into the three species which are listed in the 'monarch' data files as '2017 common_ramets', '2017 swamp_ramets', and '2017 butterfly_ramets', for each year.

- Eggs and Larvae: breakout by species and year as described in bullet above

- Eggs and Larvae: in every cell for which the value is zero because there was no milkweed to survey I would like to have the zero replaced with a "blacked out cell" or dash or something to communicate a difference between a true zero where milkweed was present vs milkweed being not present, therefore resulting in no eggs or larvae

**Comment by nulloa** [comment]
Make a note in caption of the table that ramets, eggs, and larvae were collected differently for 2016.

**Comment by nulloa** [comment]
Also look at figures.

**Comment by nulloa** [comment]
This has been done. Do you want to break out the plots the same way? I think it might be best to keep them as is. @sethapp

**Comment by nulloa** [comment]
The order might still need some work.

**Comment by sethapp** [comment]
@nulloa Something is wrong with the data being read in for (see below)...as the values are all zero in the table

- 2017 and 2018 ramets

- 2017 and 2018 eggs

- 2017 and 2018 larvae

---
2016 data does not exist for 'butterfly ramets', 'common ramets', 'swamp ramets', '2016 butterfly eggs', '2016 common eggs', '2016 swamp eggs', '2016 butterfly larvae', '2016 common larvae', '2016 swamp larvae' and this is why all of these are zero. I think we should remove them from the table? Or we could put NA on all of these.

---
we also need to find a way to display the whole table (currently we can only see half the sites). Putting transect names vertically may give more space and maybe we have to regenerate/continue the table on a second page to be able to see it all

**Comment by nulloa** [comment]
Got it done in 8ef24d0334fd295ea21270cd36033e0a00c02b50. Can you look it over @sethapp ?

**Comment by sethapp** [comment]
@nulloa 

2016 ramets, 2016 eggs, 2016 larvae all say they are zero which is not correct. The previous iteration had all of these correct.



Copied from earlier comment in this thread and still true:
2016 data does not exist for '2016 butterfly ramets', '2016 common ramets', '2016 swamp ramets', '2016 butterfly eggs', '2016 common eggs', '2016 swamp eggs', '2016 butterfly larvae', '2016 common larvae', '2016 swamp larvae' and this is why all of these are zero. I think we should remove them from the table? Or we could put NA on all of these.

**Comment by nulloa** [comment]
Done here eb0b65fdc7f4e442837055190d21eef1483cd7a5

I removed the rows with all zeros. Let me know what you think.
