### ISSUE TITLE
Pork Tables and Graphs

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch_figuresAndTables#19]
Create report similar to nectar for pork sites with nectar and ramets datasets.

Grab pork sites from `transect$grant=="pork"`.

**Comment by nulloa** [comment]
@sethapp Can you take a look at the report in 959ae7811d840570cd83171bca4f63d197cacad5

It looks pretty bare. Is it correct that 2017 shouldn't have data in some cases? If so I can remove the empty tables.

Also what is a good title?

**Comment by sethapp** [comment]
Issue: Table 1,2,3,8 contain values for pre5, pre6, pre7, pre8 but **all other tables do not**. My guess for this issue is that these sites were not renamed correctly...

Something didn't transition from 
pre3a -> pre5a
pre3b -> pre6a
pre4a -> pre7a
pre4b -> pre8a
and this is why there are no numbers for all tables/figures other than tables 1,2,3,8

**Comment by sethapp** [comment]
I checked all the data and it is correct that there were no ramets milkweeds detected in 2017 at any of the 'pork' sites . Removing the tables is good but it would be good to include a note saying something like 'no milkweed ramets of any milkweed species were detected at pork sites during the nectar surveys of 2017'

**Comment by nulloa** [comment]
Ok I found out the reason. The survey files haven't been updated and so the survey data frame is incorrect. I'll need to fix that then everything else should be fine.

**Comment by nulloa** [comment]
Also title? Or does the title even matter?

**Comment by sethapp** [comment]
Put Figure 4 right before figure 5, after table 6. Also, can we add a heatmap for 2016 nectar data density (all species; not planted vs non planted)? It would become figure 4 and all other figures would gain a number. If we do this we'll need to adjust the numbering of the figures in the paragraphs below.

[Title] 
"Summary Statistics: Establishing Monarch Butterfly Breeding Habitat on Iowa Swine Production Sites" 

[Summary paragraph]
Table 1, 2, and 3 provide mean count of nectar plant species averaged across all data collection events within a year. Values in table represent the specific floral counting unit for each species (flower head, ramet [stem], spike, or umbel) and is not associated with number of plants. Floral counting units differ between species. Table 4, 5, and 6 provide nectar plant species floral unit density (per m2) averaged
across all data collection events within a year. Tables 7 and 8 provide mean counts of milkweed ramets. This data is unavailable for 2016 and therefore 2016 does not associated milkweed ramet tables or figures. Tables 9 and 10 provide mean density of milkweed ramets.  

Figures 1, 2, 3, and 4 are heatmaps which plot the log density of species floral counting units (planted as part of the seed mix and non-planted species) with transects on the columns and species on the rows; transects are sorted by average density and species are sorted by average presence. Figure 5 is a heatmap which plots the log density of milkweed ramets with transects on the columns and species on the rows; transects are sorted by average density and species are sorted by average presence.

**Comment by nulloa** [comment]
Ok, I think I got it all figured out in 718495d85ebf043f2d975026472a186ed221a96b

I'm not sure if the order is all figured out but it was hard to keep track of what you said given the numbers changed. So just let me know if you want to rearrange things.

**Comment by sethapp** [comment]
Change page 5 to page 8 (Figure 1 and 2 follow table 6 and precede figure 3) and it's fine. I did this myself and turned in the report 5 minutes ago. Thanks so much for your help!
