### ISSUE TITLE
Nectar Figures: Planted and Non Planted in Same Heat Map

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#21]
@nulloa 

It appears the PDF generated no longer has a heat map that includes both planted and non planted species in the same heat map (with three different heat maps for the three existing years). It appears it should be on page 5 but currently the page is blank.

**Comment by nulloa** [comment]
Did you want these organized the same way as the others?

**Comment by nulloa** [comment]
I made the decision to do it that way. We can change it if we need to.
