### ISSUE TITLE
Inflorescence Figure

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#23]
Nehemias if you want to reassign Jarad because you didn't create this figure, go ahead and do so. 

Let's make a second set of figures (both for inflorescence and species richness) that looks stylistically like the other figures produced and is faceted by grant (like the other figures). Average the inflorescences and richness across each year and chart it with each line being a transect (like we have with the other data).

The figure has a number of issues which we have dealt with in almost all other figures/tables.

The pre sites need to be renamed with their new names. The current figure is strange in that not only does it include things like pre1a and pre1b (both of which aren't showing 2016 data for some reason) but also a pre 1 (only showing 2016 data for some reason). This trend is true for all pre sites. 

van2 should be renamed dav1

Uth 1, uth 2, sie1 should be removed as they were never planted.

Zeros: if a round had a zero for inflorescences or species richness the value isn't showing up. This is an issue that is true for almost all data which contains zeros and is issue '#1 in ISUmonarch repo

**Comment by nulloa** [comment]
First pass is at 6638f3439b8e829bdcb27ca4a2360a2c365f02a3

**Comment by nulloa** [comment]
Change so richness is only counting one species even if shows up in multiple rounds.

**Comment by nulloa** [comment]
I fixed the counts of richness and fixed the log scales. The default log by ggplot does log10 so that has been changed. f09faf210d7f32cad59b54d0fcfa924e3def0ea5
