### ISSUE TITLE
Bee table

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch_figuresAndTables#25]
`bee %>% group_by(transectID, year, `Bee Species`) %>% summarize(count = sum(count)) %>% spread(transectID, count, fill="--") `

**Comment by jarad** [comment]
```
bee %>% 
  rename(common_name = `Nectar Plant Species`) %>%
  left_join(species, by="common_name") %>%
  group_by(transectID, year, `Bee Species`, native_introduced_both) %>% 
  summarize(count = sum(count)) %>% 
  spread(transectID, count, fill="--") %>% tail(20)


bee %>% 
  # rename(common_name = `Nectar Plant Species`) %>%
  # left_join(species, by="common_name") %>%
  filter(year == 2018) %>%
  group_by(transectID, year, `Bee Species`, `Nectar Plant Species`) %>% 
  summarize(count = sum(count)) %>% 
  spread(transectID, count, fill="-") %>% as.data.frame

```

**Comment by nulloa** [comment]
I can't quite remember what we wanted here but we can look at it tomorrow. First pass is at 9552d82a7ce499d5d16470a1e46ba0e4d507599f

**Comment by nulloa** [comment]
In Table 1:
 - colname `native_introduced_both` -> `Native Status`
 - remove 'bee' from `Bee Species` column

New tables:
 - overall bee counts for each year summed across all bee species. So 3 observations.
 - broken down by year and bee species

To consider leaving out uthe1 & uthe2

**Comment by nulloa** [comment]
This has been done at 6753ff9233bcf9f794dcb14b7349e0e75b444349

I feel like for Table 2 we may want percentages instead of mean counts? thoughts @sethapp ?

**Comment by nulloa** [comment]
Turn Table 2 into sum table than mean table

Turn Table 2 into multiple tables, one table per bee type. Look at percentages vs sums.

Consider the how to plot the above tables.

**Comment by nulloa** [comment]
Done in 0f952be275d3d287dce9efb3f392ab9c037be2bf
