### ISSUE TITLE
NCIG Report: Table 1&2

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch_figuresAndTables#3]
Here is a copy of the issue in the data repo:

Jarad
> From Seth:
>
> Sum(round 1,2,3) [sum all data points for each species for each round]  /  # of rounds [usually 3]
> ·         Here are the values I did hard checks on:
> 
> * Table 1
>   
>   * All1 red clover: 1.5 in current table, 4 is true answer
>   * All1 white clover: 106 in current table, 375.3 is true answer
>   * Pio1 black eyed susan: 52.6 in current table, 210.3 is true answer
> * Table 2
>   
>   * Nkn1 birdsfoot trefoil: 57.4 in current table, 574.3 is true answer
>   * Nor1 blue vervain: 150.3 in current table, 501 is true answer

Jarad
> The code wasn't summing across the rounds first. Some of the answers now match your "true answers" but some don't. For example, there is only 2 rounds (round 1 and 3) for all1 and thus I believe the true answer should be 6.

Seth
> I think the true answer still is 4 and here's my explanation for what I think is going on:
>
> For 'all1 red clover' the values are R1: 2, R2: 0, R3: 10. So a total of 12 red clover/3 rounds=4. Based on what you said, the formula is counting all rounds which don't have 'red clover' as an entry as NA instead of 0. All rounds where data is collected but a species is not recorded means the species was a zero and contributes to the overall average.

Jarad
> I agree. So what we need is to extract from the files every survey that occurred whether or not any species was recorded.

**Comment by nulloa** [comment]
@sethapp I've updated a new pdf. It looks horrible but the tables have been updated. Do you want to take a quick look and see if we are on the right track?

[https://github.com/jarad/ISUmonarch_figuresAndTables/blob/master/NCIG/Nectar/NCIG-Nectar.pdf](url)

**Comment by sethapp** [comment]
@nulloa 
Table 1 and 2 have the same issue as is mentioned above; failing to count zeros and include them in calculations. 

Table 1: The formula doesn't know that rounds which do not contain a specific species should be a zero for that species. The formula is creating the average based on the number of rounds for which there is data. For example: 
gro1 2016
alfalfa: 
R1: 591
R2: 225
R3: 0
average should be 816/3=**272** but instead it's doing 816/2=408.

**Comment by sethapp** [comment]
I just realized that this is the same issue as is mentioned above

**Comment by sethapp** [comment]
@nulloa 
Table 4: I can't figure out what the issue is but I know the numbers are not correct. 
all1 2016
bladder campion: count R1, R2, R3: 0, 0, 3; /50= 0, 0, 0.6 Average= **0.02** not 6
common dandelion: count R1, R2, R3: 1, 0, 3; /50= .02, 0, .06 average= **0.027** not 4
common mullein: count R1, R2, R3: 0, 0, 5; /50= 0, 0, 0.1 average= **0.03** not 10
byd2 2016
white clover: count R1, R2, R3: 24, 620, 564; /100= 0.24, 6.2, 5.64 average= **4.027** not 757

Table 5: labels are off the page so I'm not sure how to check it.

**Comment by nulloa** [comment]
@sethapp I think I know what is going on. Now that I have an idea of what is supposed to be there I can try and figure it out. Thanks for the input.

**Comment by nulloa** [comment]
The new pdf has got this figured out though there needs to be discussion on how we tackle these large tables.

**Comment by sethapp** [comment]
I believe the numbers are correct now.

A few quick ideas on large tables:
- Maybe we just need an excel file for any table that's pretty large. Somehow I need to be able to see this data in a large display even if it won't fit on a page. Maybe the end consumer can view it if they want but the main point is the analysis derived from it. End consumer may care about the 'density' tables but certainly won't care about the 'count' tables.
- If there are too many columns or rows we may just need to list tables on multiple pages
- Reducing columns: We could group the plots by some similar characteristic and make different tables
- Reducing rows: As previously discussed, we will have separate groups (which could be split into separate tables) for planted native species, non planted native species, non-native species, both species.
- Reducing rows: we could say we are only listing species which achieved a density of greater than 0.1m2 in a separate table.

**Comment by nulloa** [comment]
@sethapp I've splitting up these tables. Heads up we split one table into 4 now so there is quite a lot of them. There are still too many transects on a table even after splitting by grant. Should we just split the transects into 3 even groups?

**Comment by nulloa** [comment]
Ways to combine tables:
 - planted and non-planted breakup of species and further breakdown non-planted into two categories
 - split up transects by grant
    - combine iacig and soy tables with a vertical black line between them
    - ncig create vertical colnames while keeping `Nectar Species` horizontal

So every table should be broken up into 9 tables.

**Comment by nulloa** [comment]
Alright so this has been done.
