### ISSUE TITLE
NCIG Report Sites to Include

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#5]
Table 1, 2, 3 only contain NCIG sites while tables 4 and 5 appear to contain all sites in the study. I think we want these reports to contain all sites in the study and later we will break them down by their specific grants. When we publish this I know we will want all the sites included in an analysis.

**Comment by nulloa** [comment]
Closed with 8a44fadc5ebe9d9f2df8631032da388db4439bbd
