### ISSUE TITLE
Sort Nectar Species

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#6]
When nectar species are sorted for the nectar data I believe this is how I want them sorted:
-Planted species (all are native)
-Non planted species
----Introduced
----Native
----Both

**Comment by sethapp** [comment]
@nulloa tell me what you think about these ideas

**Grouping ideas** I still need to think this through
With all the 'survey' calculations is this even possible? To group transects or group species together?

Nectar species
-Group similar species (all sunflowers, all non native legumes, etc)
---Would need to develop species groupings and create a document
---~Can only group species that have same counting unit
Sites
-Group by vegetation previous to establishment?

**Comment by nulloa** [comment]
@sethapp I think I understand what you are saying but to make sure, this is what is in the `species` data.frame:

```
> head(species)
                common_name field_count_unit     genus                                            species
1           common milkweed            umbel Asclepias                                            syriaca
2             deptford pink             head  Dianthus                                            armeria
3 panicledleaf tick trefoil            ramet Desmodium                                        paniculatum
4                 smartweed            spike Polygonum pensylvanicum_persicaria_amphibium_hydropiperoides
5            swamp milkweed            umbel Asclepias                                          incarnata
6        butterfly milkweed            umbel Asclepias                                           tuberosa
  native_introduced_both planted_non_planted technical_count inflorescence_name_when_technical
1                 native             planted    simple umbel                                  
2             introduced         non planted                                                  
3                 native         non planted                                                  
4                   both         non planted          raceme                     racemic heads
5                 native             planted coumpound umbel                                  
6                 native             planted coumpound umbel                                  
```


So when you say 

> -Group similar species (all sunflowers, all non native legumes, etc)

Does that mean use `genus` as grouping variable?


Do we have this data?
> -Group by vegetation previous to establishment?

**Comment by sethapp** [comment]
The groupings I am suggesting do not currently exist in any files. 

For the species data.frame I would have to create a new column (or a new document) which lists what group each species is part of...and develop some rules so that if we encounter new species in 2019 they will be easy to group.

Previous vegetation would roughly be based on the column 'original_vegetation_2016' from https://github.com/jarad/ISUmonarch/blob/master/data-raw/metadata/Site%20Info%20Metadata.xlsx  but this column is currently just written as notes and not as specified treatments. I would need to clean it up.

**Comment by nulloa** [comment]
For ordering, think about 
- native 
   - planted
   - non-planted
- non-native
   - planted
   - non-planted

**Comment by jarad** [comment]
Do we have any non-native planted? I'd be surprised if we planted any non-natives.

**Comment by sethapp** [comment]
Correct Jarad. We did not plant any introduced species. 

That's why they are grouped in the fashion they are at the start of this issue.

**Comment by jarad** [comment]
Ah yes, there it is. For the ordering we want Planted, Native non-planted, Both non-planted, and then Introduced non-planted.
