### ISSUE TITLE
Add heatmaps to report

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch_figuresAndTables#7]
Add heatmaps as another way of displaying the information in the tables

**Comment by nulloa** [comment]
@sethapp I've added them to the last commit 3e791bb7b98ad70fdfcec8ddd74646b735fbd6ac

Let me know what you think of them.

**Comment by sethapp** [comment]
It's fun to see a visual representation of the data for the first time. With that said, it's not very useful. It's pretty difficult to mentally draw the lines to figure out which transect corresponds to the nectar species. A few data points are very high which skews the scale high and makes it impossible to see any differences among the normal, low population nectar species (they're all the same color).

**Comment by jarad** [comment]
We could probably add a grid and plot on a log scale.

**Comment by nulloa** [comment]
I've added the gird lines and plotted on the log scale. Both the nectar and ramet are up if you want to take a look @sethapp

**Comment by sethapp** [comment]
This is much more useful. I think this is a good way to attempt to visually display this large of a set of data. Although it does take some effort to connect the lines I'm not sure how else it could be done. 

One issue: the x axis labels do not line up with the tick marks. They're all shifted slightly right of the tick (and the column).
