### ISSUE TITLE
Planted species heatmaps

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch_figuresAndTables#8]
For nectar data, create heatmaps for density of species planted with transects on the columns and species on the rows sorting transects by average density and sorting species by average density. 

Also, create a binary heatmap (density>0).

**Comment by jarad** [comment]
Create these same heatmaps for unplanted species as well.

**Comment by sethapp** [comment]
For the unplanted species it would be helpful if we could cluster the species by their native status as well: native, introduced, both (don't combine the species data, just list the species by each other in the three groups)

**Comment by nulloa** [comment]
> For the unplanted species it would be helpful if we could cluster the species by their native status as well: native, introduced, both (don't combine the species data, just list the species by each other in the three groups)

We'll have to talk more about this in person to make sure I understand what you want, but the first pass at these plots are up: d00ea54d68152536be27f7f0ebf718f370944fcb

**Comment by nulloa** [comment]
Facet by:
- native vs non-native
- planted vs non-planted
- year

**Comment by nulloa** [comment]
Add captions to these plots
