### ISSUE TITLE
Ramet Tables

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch_figuresAndTables#9]
The ramet tables should not include the 'milkweed strip: common milkweed ramet'. This should go in it's own table and only contain the sites arm1b, all2a, ber3a, and nkn1a.

Also, can we make the heat map columns shorter? They don't need to be so tall.

**Comment by nulloa** [comment]
Should the heatmaps be separated as well?

**Comment by sethapp** [comment]
Yes, I should have said both heat maps and tables should be separate. 

Also, if making the heat map bars shorter is challenging don't worry about it.

**Comment by nulloa** [comment]
This has been done
